"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Tải biến môi trường từ file .env
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-unsafe-secret-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'channels',
    'rest_framework',      # <--- BẠN ĐANG THIẾU DÒNG NÀY
    'rest_framework_gis',  # Hỗ trợ bản đồ
    'corsheaders',         # Hỗ trợ React gọi API
    'django_filters',      # Hỗ trợ lọc
    'leaflet',

    'users',
    'shops',
    'social',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # Dùng engine này hỗ trợ bản đồ
        'NAME': 'mydb',
        'USER': 'myuser',
        'PASSWORD': 'mypassword',
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': '5433',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
CORS_ALLOW_ALL_ORIGINS = True # Chỉ dùng khi dev, production thì điền domain cụ thể

AUTH_USER_MODEL = 'users.User'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Cấu hình REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, # Mỗi trang trả về 10 kết quả (React sẽ làm nút "Load more")
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Jazzmin admin interface configuration
JAZZMIN_SETTINGS = {
    "site_title": "Can Tho Map Admin",
    "site_header": "GIS Admin",
    "site_brand": "🗺️ GIS Admin",
    "site_logo": None,
    "welcome_sign": "Welcome back, GIS Administrator",
    "copyright": "Quang Huy GIS Project",

    "search_model": ["users.User", "shops.Store"],
    "user_avatar": "avatar",

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-layer-group",
        "users.User": "fas fa-user-circle",
        "shops.Store": "fas fa-store",
        "shops.Category": "fas fa-tags",
        "shops.StoreImage": "fas fa-images",
        "shops.ApprovalProfile": "fas fa-clipboard-check",
        "social.Review": "fas fa-star",
    },

    # Sidebar style
    "sidebar": "sidebar-dark-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    "show_ui_builder": False,

    "custom_css": "css/admin_fix.css",
    "custom_js": "js/admin_custom.js",
}

# Jazzmin UI colour tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (10.0452, 105.7469), # Tọa độ Cần Thơ
    'DEFAULT_ZOOM': 12,
    'MIN_ZOOM': 10,
    'MAX_ZOOM': 21,
    'SCALE': 'both',
    'ATTRIBUTION_PREFIX': 'Bản đồ Cần Thơ',
    'TILES': [
        ('Bản đồ tiêu chuẩn (MapTiler)', f"https://api.maptiler.com/maps/topo-v4/{{z}}/{{x}}/{{y}}@2x.png?key={os.environ.get('MAPTILER_KEY', '')}", {
            'attribution': '&copy; <a href="https://www.maptiler.com/copyright/">MapTiler</a>',
            'maxNativeZoom': 20,
            'maxZoom': 21
        }),
        ('Bản đồ vệ tinh (ArcGIS)', 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
            'attribution': 'Tiles &copy; Esri',
            'maxNativeZoom': 19,
            'maxZoom': 21
        }),
    ],
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# GIS (GDAL/GEOS) Configuration for Windows using PostgreSQL installation
if os.name == 'nt':
    os.environ['PATH'] += r';C:\Program Files\PostgreSQL\16\bin'
    GDAL_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\16\bin\libgdal-35.dll'
    GEOS_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\16\bin\libgeos_c.dll'