# Generated by Django 4.2.30 on 2026-06-24 04:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_up', models.DateTimeField(auto_now_add=True)),
                ('date_sign', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Category Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, help_text="Nhiều số điện thoại ngăn cách bằng ' | ', VD: 0901234567 | 0281234567", max_length=100, null=True, verbose_name='Store Phone Number')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Store Email')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates')),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50, verbose_name='Store Status')),
                ('describe', models.TextField(blank=True)),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('rating_avg', models.FloatField(default=0.0, verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Review Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Image')),
                ('describe', models.TextField(blank=True)),
                ('state', models.CharField(max_length=50)),
                ('time_up', models.TimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shops.store')),
            ],
        ),
    ]
